### ISSUE TITLE
Rational vs Floats

### ISSUE THREAD

**Issue by mdavezac** [JuliaMath/FixedPointDecimals.jl#17]
I can't help but notice that `convert(FD, 0.333)` is valid, whereas `convert(FD, 1//3)` isn't (throws InexactError). The difference comes down how adding `round` in `convert(FD, ::Rational)`.

Is there a good reason the behaviour of Rational and Float are not consistent?

**Comment by TotalVerb** [comment]
We do support e.g. `round(FD, 1//3)` that does the rounding.

In general I am ambivalent about implicitly losing precision, so I prefer the `InexactError` unless one uses an explicit `round`. You are right that converting from a Float64 may also lose precision, so in theory that should also throw `InexactError`, but `FD(0.02)` is nice notation and we would lose that, since 0.02 is actually 0.0200000000000000004163336342344337026588618755340576171875...

**Comment by mdavezac** [comment]
Okay, I see your point, though personally I would rather behavior were consistent across all number types. Thanks for pointing me to `round`. Cheers!
