### ISSUE TITLE
`==` should not leak promotion failure

### ISSUE THREAD

**Issue by mbarbar** [JuliaMath/FixedPointDecimals.jl#82]
```
julia> x = FixedDecimal{Int128, 33}(10000)
FixedDecimal{Int128,33}(10000.000000000000000000000000000000000)

julia> y = FixedDecimal{Int128, 38}(0)
FixedDecimal{Int128,38}(0.00000000000000000000000000000000000000)

julia> x == y
ERROR: InexactError: Int128(1000000000000000000000000000000000000000000)
Stacktrace:
 [1] Int128(x::BigInt)
   @ Base.GMP ./gmp.jl:373
 [2] convert
   @ ~/.julia/packages/FixedPointDecimals/Eseyj/src/FixedPointDecimals.jl:313 [inlined]
 [3] _promote
   @ ./promotion.jl:358 [inlined]
 [4] promote
   @ ./promotion.jl:381 [inlined]
 [5] ==(x::FixedDecimal{Int128, 33}, y::FixedDecimal{Int128, 38})
   @ Base ./promotion.jl:449
 [6] top-level scope
   @ REPL[5]:1
```

This should be not equal rather than `InexactError` (an implementation detail). Checking representability in `==` should solve this.

**Comment by NHDaly** [comment]
I liked the suggestion on slack from @davidwzhao that equality checks should be _intersecting,_ or narrowing, the larger type down to the smaller one, rather than promoting the smaller type to the larger! If the value of the larger type cannot be represented in the smaller type, you already know that the values are not equal.

But in either case, the point is that we should be checking whether the values will fit in each other's types, rather than blindly attempting the conversion and then throwing. 👍

**Comment by mbarbar** [comment]
Do we explicitly overload `==` for different FD types like...
```
Base.:(==)(x::S, y::T) where {S <: FD, T <:FD} = ...
```
to implement this suggestion?

In that case, we'd need to do the same for other comparison functions. The common thread is promotion of course, but I think promotion is working as expected.

**Comment by NHDaly** [comment]
Yep! But we can use code generation to reuse (almost) the same implementation for all the comparisons.
